[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py37,py38
skipsdist = True

[commands]
pytest = pytest -p no:cacheprovider --cov=pbatch --cov-report term-missing {posargs} tests/

[testenv]
depends = clean-coverage
setenv =
    PYTHONDONTWRITEBYTECODE = 1
parallel_show_output = True
deps = -e .[dev]
whitelist_externals = pytest
commands = {[commands]pytest}

[testenv:py38]
commands = {[commands]pytest} -m "not performance"
"""
