[tool.isort]
profile = "black"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py37,py38

[testenv]
depends = clean-coverage
setenv =
    PYTHONDONTWRITEBYTECODE = 1
parallel_show_output = True
whitelist_externals = pytest
commands = pytest -p no:cacheprovider --cov=pbatch --cov-report term-missing {posargs} tests/
"""
