name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
    pull_request: {}

jobs:
  test:
    name: test python ${{ matrix.python-version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        python-version: ['3.7', '3.8']
    env:
      PYTHON: ${{ matrix.python-version }}
      OS: ${{ matrix.os }}

    runs-on: ${{ format('{0}-latest', matrix.os) }}
    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: install
      run: make install-dev
    - name: test
      run: make test
    - name: coverage
      run: make coverage

    - uses: codecov/codecov-action@v1.0.13
      with:
        file: coverage.xml
        env_vars: PYTHON,OS

  deploy:
    name: build and deploy
    needs: test
    if: "success() && startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/check@v2

    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: install
      run: make install-dev

    - name: build
      run: make build

    - name: upload to pypi
      run: twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.pypi_token }}
